"""auto_migration

Revision ID: c4f9fd3bb97f
Revises: 20260721_0001
Create Date: 2026-08-02 14:05:52.873104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

revision: str = 'c4f9fd3bb97f'
down_revision: Union[str, Sequence[str], None] = '20260721_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.drop_column('auths', 'access_token')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.add_column('auths', sa.Column('access_token', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_column('auths', 'expiration')
    # ### end Alembic commands ###
